
<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
th { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%} .post-age{width:2%}
</style>

<table>
  <tr>
    <th class="post-id">Id</th>
    <th class="post-name">Name</th>
    <th class="post-age">Age</th>
    <th>Content</th>
  </tr>
    <?php
        foreach ($block->getPostCollection() as $key=>$post){
            echo '<tr>
                    <td>'.$post->getPostId().'</td>
                    <td>'.$post->getName().'</td>
                    <td>'.$post->getAge().'</td>
                    <td>'.$post->getContent().'</td>
                  </tr>';
        }
    ?>
</table>

</body>
</html>